'use client'
import { Provider } from "react-redux";
import "./globals.css";
import { Inter } from "next/font/google";

import { store } from "@/store";
const inter = Inter({ subsets: ["latin"] });

 const metadata = {
  title: "Query",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Provider store={store}>
         <html lang="en">
            <body className={inter.className}>{children}</body>
          </html>
    </Provider>
   
  );
}
